version: '3.1'

services:
  gunicorn-freeze:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8888'
    ports:
      - "8888:8888"
    environment:
      - WORKER_CLASS=sync
      - NUM_WORKERS=5
      - BACKLOG=4096
      - TIMEOUT=3600